import Navbar from "@/components/navbar/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "note-sharing | notes",
	description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className="container flex min-h-[100dvh] flex-col ">
			<Navbar />
			{children}
		</div>
	);
}
